version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 80:3000
    env_file:
      - ./.env
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust