pvt_key         = "~/.ssh/id_rsa"
datadog_api_url = "https://app.datadoghq.eu/api/v1/validate"
my_site         = "http://shephik.ru"
my_site_https   = "https://shephik.ru"
instance_name   = "shephik.ru"